version: '3'

services:
  proxy:
    image: nginx:1.15 # this will use the latest version of 1.15.x
    ports:
      - '80:80'       # expose 80 on the host and sents it to 80 in the container
      - '443:443'     # expose 443 on the host and sents it to 443 in the container
    volumes:
      - ./nginx/:/etc/nginx/:ro
                      # mounts the persistant nginx.conf inside the container as readonly
  web:
    image: httpd      # this will use httpd:latest

