version: '3'

services:
    proxy:
        image: nginx:1.15 # this will use the latest version of 1.15.x
        ports:
            - '80:80'       # expose 80 on the host and sents it to 80 in the container
            - '443:443'     # expose 443 on the host and sents it to 443 in the container
        volumes:            # mounts the nginx config folder inside the container as readonly
            - ./nginx/:/etc/nginx/
        networks:           # uses the frontend network to pass trafic into the containers
            - frontend

    API:
        image: httpd        # this will use httpd:latest and should be changed to the actual API once it is ready
        networks:           # uses both the frontend and backend network 
            - frontend
            - backend     
networks:
    frontend:               # creates a new network for frontend traffic
    backend:                # creates a new network for backend traffic
